
project:
  name: "Algorithmic Summarization Engine"
  version: "2.1"

io:
  input_dir: "data/raw"
  output_dir: "data/outputs"
  default_input_file: "input.txt"

preprocessing:
  min_sentence_length: 10

classic:
  #textrank, frequency
  method: "textrank" 

textrank:
  similarity_threshold: 0.1
  damping_factor: 0.85
  max_iterations: 50
  convergence_threshold: 0.0001

llm:
  mode: "api" 
  model_name: "gemini-2.0-flash"
  api_key_env_var: "METIS_API_KEY"

hybrid:
  alpha: 0.6
  beta: 0.4
  final_summary_count: 3